/** String resources for the Topic Governance curator panel (Phase 13 Stage 4). SSOT — no hardcoded UI text in the view/viewmodel. */
export const TOPIC_GOVERNANCE_STRINGS = {
  tabLabel: 'Topic Governance',
  queues: {
    pendingCandidates: 'Pending candidates',
    provisionalTopics: 'Provisional topics',
    aliasCollisions: 'Alias collisions',
    nearDuplicateCandidates: 'Possible duplicates',
    assignmentDisagreements: 'Assignment disagreements'
  } as const,
  loading: 'Loading…',
  empty: 'Nothing to review in this queue.',
  errorPrefix: 'Error: ',
  approve: 'Approve',
  reject: 'Reject',
  suppress: 'Suppress topic',
  restore: 'Restore topic',
  merge: 'Merge into…',
  reverseMerge: 'Reverse merge',
  viewEvidence: 'View evidence',
  preview: 'Preview',
  confirmAndApply: 'Confirm and apply',
  cancel: 'Cancel',
  submitting: 'Applying…',
  confirmSuppress: 'Suppress this topic? It will stop being publicly visible until restored, and its live assignments will be queued for reclassification.',
  confirmRestore: 'Restore this topic to active and published?',
  confirmApproveCandidate: 'Approve this candidate and publish the linked topic?',
  confirmRejectCandidate: 'Reject this candidate? This cannot be undone from this panel.',
  evidenceTitle: 'Evidence',
  evidenceSpan: 'Span',
  evidenceSource: 'Source',
  independenceTitle: 'Source independence',
  mentionCount: 'Mentions',
  independentSourceCount: 'Independent sources',
  assignmentDiffTitle: 'Assignment history',
  classifierVersion: 'Classifier version',
  conflictError: 'This record changed since it was loaded — refresh the queue and try again.',
  refresh: 'Refresh'
} as const;
