import { TopicKnowledgeBaseViewModel } from '../../viewmodels/TopicKnowledgeBaseViewModel.js';
import topicStrings from '../../resources/topicStrings.js';
import { renderTopicArticleCard } from './TopicArticleCard.js';

export function renderTopicKnowledgeBaseView(vm: TopicKnowledgeBaseViewModel): HTMLElement {
  const root = document.createElement('section'); root.className = 'dw-topic-knowledge-base';
  const render = () => { root.innerHTML = ''; const page = vm.getPage(); if (vm.getIsLoading() && !page) { root.textContent = topicStrings.loading; return; } if (!page?.topic) { root.textContent = topicStrings.unavailable; return; } const heading = document.createElement('h2'); heading.textContent = `${page.topic.displayHashtag} — ${topicStrings.heading}`; root.appendChild(heading); const description = document.createElement('p'); description.textContent = page.topic.description ?? topicStrings.noDescription; root.appendChild(description); if (page.error) { const error = document.createElement('p'); error.className = 'dw-topic-error'; error.textContent = topicStrings.unavailable; root.appendChild(error); return; } const stats = document.createElement('dl'); stats.className = 'dw-topic-stats'; const rows: Array<[string, string]> = [[topicStrings.articles, `${page.totalCount} ${topicStrings.topicCount}`], [topicStrings.firstObserved, page.firstObservedAt ?? '—'], [topicStrings.latestObserved, page.latestObservedAt ?? '—']]; for (const [label, value] of rows) { const term = document.createElement('dt'); term.textContent = label; const detail = document.createElement('dd'); detail.textContent = value; stats.append(term, detail); } root.appendChild(stats); if (!page.articles.length) { const empty = document.createElement('p'); empty.textContent = topicStrings.empty; root.appendChild(empty); } else { page.articles.forEach((article) => root.appendChild(renderTopicArticleCard(article))); } const related = document.createElement('section'); const relatedHeading = document.createElement('h3'); relatedHeading.textContent = topicStrings.relatedTopics; related.appendChild(relatedHeading); const relatedList = document.createElement('ul'); if (page.related.length) page.related.forEach((topic) => { const item = document.createElement('li'); item.textContent = topic.displayHashtag; relatedList.appendChild(item); }); else relatedList.textContent = topicStrings.noRelatedTopics; related.appendChild(relatedList); root.appendChild(related); const threads = [...new Set(page.articles.flatMap((article) => article.relatedThreadIds))]; const threadSection = document.createElement('section'); const threadHeading = document.createElement('h3'); threadHeading.textContent = topicStrings.storyThreads; threadSection.appendChild(threadHeading); const threadList = document.createElement('ul'); if (threads.length) threads.forEach((id) => { const item = document.createElement('li'); item.textContent = id; threadList.appendChild(item); }); else threadList.textContent = topicStrings.noStoryThreads; threadSection.appendChild(threadList); root.appendChild(threadSection); if (vm.hasMore()) { const more = document.createElement('button'); more.type = 'button'; more.textContent = topicStrings.loadMore; more.addEventListener('click', () => void vm.load(true)); root.appendChild(more); } };
  vm.subscribe(render); void vm.load(); render(); return root;
}
